import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { BookOpen, Download, Pencil, Plus, Printer, QrCode, Search, ShieldCheck, X } from 'lucide-react'
import { useAuth } from '@/context/AuthContext'
import { supabase } from '@/lib/supabase'

type Drug = { id:string; generic_name:string; compatible_solutions:string|null; preparation_method:string|null; injection_duration:string|null; other_precautions:string|null; is_active:boolean; qr_enabled:boolean }
type Form = { generic_name:string; compatible_solutions:string; preparation_method:string; injection_duration:string; other_precautions:string }
const EMPTY:Form={generic_name:'',compatible_solutions:'',preparation_method:'',injection_duration:'',other_precautions:''}
const BASE='https://had-smart.vercel.app'
const learnUrl=(id:string)=>`${BASE}/learn/${encodeURIComponent(id)}`
const qrUrl=(id:string)=>`https://api.qrserver.com/v1/create-qr-code/?size=1200x1200&margin=24&data=${encodeURIComponent(learnUrl(id))}`
const lines=(v:string|null|undefined)=>String(v??'').replace(/\r\n/g,'\n').replace(/\r/g,'\n').replace(/\s*\|\s*/g,'\n').trim()
const esc=(v:string|null|undefined)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;')
const shorten=(v:string|null|undefined,max:number)=>{const s=lines(v)||'—';return s.length<=max?s:`${s.slice(0,Math.max(1,max-32)).trimEnd()}… ดูข้อมูลเต็มผ่าน SCAN TO LEARN`}

function profile(d:Drug){const n=[d.compatible_solutions,d.preparation_method,d.injection_duration,d.other_precautions].reduce((a,v)=>a+lines(v).length,0);return n>900?{qr:3.65,max:105}:n>600?{qr:3.95,max:135}:n>350?{qr:4.25,max:160}:{qr:4.5,max:190}}

function cardHtml(d:Drug){const p=profile(d);const sec=(title:string,value:string|null,warn=false)=>`<section class="sec ${warn?'warn':''}"><b>${esc(title)}</b><div>${esc(shorten(value,p.max))}</div></section>`;return `<!doctype html><html lang="th"><head><meta charset="utf-8"><title>HAD Smart - ${esc(d.generic_name)}</title><style>@page{size:9.5cm 20cm;margin:0}*{box-sizing:border-box}html,body{margin:0;width:9.5cm;height:20cm}body{font-family:Arial,'Noto Sans Thai',Tahoma,sans-serif;color:#123}.card{width:9.5cm;height:20cm;padding:.42cm;display:flex;flex-direction:column;gap:.14cm;overflow:hidden;background:linear-gradient(160deg,#fff,#f3fbfc);border:.05cm solid #087e8b;border-radius:.2cm}.head{display:flex;justify-content:space-between;gap:4px;border-bottom:1px solid #c9e3e6;padding-bottom:5px}.head strong{font-size:10.5pt;color:#075985}.badge{font-size:5.8pt;font-weight:800;color:#08756b;background:#e1f4f0;padding:3px 5px;border-radius:12px}.label{font-size:6.7pt;color:#64748b;font-weight:700}.name{font-size:16pt;line-height:1.05;font-weight:800;color:#064e6b;max-height:1cm;overflow:hidden}.qrbox{text-align:center}.qr{width:${p.qr}cm;height:${p.qr}cm;padding:3px;border:1px solid #d7e7eb;border-radius:7px}.sec{flex:1;min-height:.8cm;max-height:2cm;overflow:hidden;border-left:4px solid #087e8b;background:#edf7f8;border-radius:6px;padding:5px 7px}.sec.warn{border-left-color:#d97706;background:#fff7ed}.sec b{display:block;font-size:6.9pt;color:#075985;margin-bottom:2px}.sec div{font-size:6.5pt;line-height:1.15;white-space:pre-wrap;overflow:hidden}.foot{margin-top:auto;border-top:1px solid #c9e3e6;padding-top:4px;text-align:center;font-size:5.3pt;color:#64748b}.foot strong{color:#08756b}</style></head><body><article class="card"><div class="head"><strong>HAD Smart • High Alert Drug</strong><span class="badge">SCAN TO LEARN</span></div><div class="label">ชื่อยา</div><div class="name">${esc(d.generic_name)}</div><div class="qrbox"><img class="qr" src="${qrUrl(d.id)}"></div>${sec('สารละลายที่ใช้ได้',d.compatible_solutions)}${sec('วิธีเตรียมยา',d.preparation_method)}${sec('ระยะเวลาที่ฉีด',d.injection_duration)}${sec('อื่นๆ / ข้อควรระวัง',d.other_precautions,true)}<div class="foot"><strong>SCAN TO LEARN</strong> • ข้อมูลยาฉบับเต็ม • ตรวจสอบคำสั่งแพทย์และแนวทางหน่วยงานก่อนใช้ยา</div></article></body></html>`}

function Field({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block text-sm font-medium text-slate-800">{label}<textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 outline-none focus:border-teal-500 focus:ring-2 focus:ring-teal-100"/></label>}

export function DrugManagementPageSmart(){const {profile:auth}=useAuth();const [drugs,setDrugs]=useState<Drug[]>([]);const [search,setSearch]=useState('');const [form,setForm]=useState<Form>(EMPTY);const [editing,setEditing]=useState<Drug|null>(null);const [card,setCard]=useState<Drug|null>(null);const [learn,setLearn]=useState<Drug|null>(null);const [showForm,setShowForm]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('')
 async function load(){const r=await supabase.from('had_drugs').select('id,generic_name,compatible_solutions,preparation_method,injection_duration,other_precautions,is_active,qr_enabled').order('generic_name');if(r.error)setError(r.error.message);else setDrugs((r.data??[]) as Drug[])}
 useEffect(()=>{if(auth?.role==='admin')void load()},[auth?.role])
 const filtered=useMemo(()=>{const q=search.toLowerCase().trim();return q?drugs.filter(d=>[d.generic_name,d.compatible_solutions,d.preparation_method,d.injection_duration,d.other_precautions,d.id].some(v=>String(v??'').toLowerCase().includes(q))):drugs},[drugs,search])
 if(auth?.role!=='admin')return null
 const adminId=auth.id
 const openNew=()=>{setEditing(null);setForm({...EMPTY});setError('');setShowForm(true)}
 const openEdit=(d:Drug)=>{setEditing(d);setForm({generic_name:d.generic_name,compatible_solutions:d.compatible_solutions??'',preparation_method:d.preparation_method??'',injection_duration:d.injection_duration??'',other_precautions:d.other_precautions??''});setError('');setShowForm(true)}
 async function save(e:FormEvent){e.preventDefault();if(!form.generic_name.trim()){setError('กรุณาระบุชื่อยา');return}setBusy(true);const data={generic_name:form.generic_name.trim(),compatible_solutions:form.compatible_solutions.trim()||null,preparation_method:form.preparation_method.trim()||null,injection_duration:form.injection_duration.trim()||null,other_precautions:form.other_precautions.trim()||null,...(editing?{}:{created_by:adminId})};const r=editing?await supabase.from('had_drugs').update(data).eq('id',editing.id):await supabase.from('had_drugs').insert(data);setBusy(false);if(r.error){setError(r.error.message);return}setMessage(editing?'บันทึกข้อมูลยาแล้ว':'เพิ่มรายการยาแล้ว');setShowForm(false);await load()}
 async function toggle(d:Drug){setBusy(true);const r=await supabase.from('had_drugs').update({is_active:!d.is_active,qr_enabled:!d.is_active}).eq('id',d.id);setBusy(false);if(r.error)setError(r.error.message);else await load()}
 async function downloadQr(d:Drug){setError('');try{const r=await fetch(qrUrl(d.id));if(!r.ok)throw new Error('ดาวน์โหลด QR ไม่สำเร็จ');const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`HAD-Smart-QR-${d.generic_name.replace(/[^\wก-๙]+/g,'-')}.png`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}catch{window.open(qrUrl(d.id),'_blank','noopener,noreferrer')}}
 function print(){if(!card)return;const w=window.open('','_blank');if(!w){setError('กรุณาอนุญาต Pop-up เพื่อพิมพ์ Card');return}w.document.write(cardHtml(card));w.document.close();w.onload=()=>setTimeout(()=>w.print(),300)}
 return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><ShieldCheck size={20} className="text-teal-700"/><h1 className="text-xl font-semibold">จัดการรายการยา • Smart Adaptive QR Card</h1></div><p className="mt-1 text-sm text-slate-500">QR ใบเดียวใช้ได้ทั้ง <b>เตรียมยา</b> และ <b>Scan to Learn</b> • ขนาด Card 9.5 × 20 ซม.</p></div><button onClick={openNew} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white"><Plus size={17}/>เพิ่มรายการยา</button></div>{message&&<div className="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-700">{message}</div>}{error&&<div className="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>}<section className="rounded-2xl border border-slate-200 bg-white p-4"><div className="relative"><Search size={17} className="absolute left-3 top-3 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="ค้นหาชื่อยา หรือข้อมูลยา" className="w-full rounded-xl border border-slate-200 py-2.5 pl-10 pr-3 outline-none"/></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b text-left text-xs text-slate-500"><th className="px-3 py-2">ชื่อยา</th><th>สารละลาย</th><th>ระยะเวลาที่ฉีด</th><th>สถานะ</th><th>จัดการ</th></tr></thead><tbody>{filtered.map(d=><tr key={d.id} className="border-b last:border-0"><td className="px-3 py-3"><b>{d.generic_name}</b><div className="text-[10px] text-slate-400">{d.id}</div></td><td className="max-w-[260px] truncate">{d.compatible_solutions||'-'}</td><td>{d.injection_duration||'-'}</td><td>{d.is_active?'ใช้งาน':'ปิดใช้งาน'}</td><td><div className="flex gap-1"><button disabled={!d.is_active||!d.qr_enabled} onClick={()=>setCard(d)} className="inline-flex items-center gap-1 rounded-lg border border-teal-600 px-2.5 py-1.5 text-xs font-semibold text-teal-700 disabled:opacity-40"><QrCode size={14}/>QR Card</button><button disabled={!d.is_active} onClick={()=>setLearn(d)} className="inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 text-xs disabled:opacity-40"><BookOpen size={14}/>Learn</button><button onClick={()=>openEdit(d)} className="inline-flex items-center gap-1 rounded-lg border px-2.5 py-1.5 text-xs"><Pencil size={14}/>แก้ไข</button><button disabled={busy} onClick={()=>void toggle(d)} className="rounded-lg border px-2.5 py-1.5 text-xs">{d.is_active?'ปิดใช้งาน':'เปิดใช้งาน'}</button></div></td></tr>)}</tbody></table></div></section>
 {showForm&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><div className="max-h-[92vh] w-full max-w-3xl overflow-auto rounded-3xl bg-white p-5"><div className="flex items-start justify-between"><div><b className="text-xs text-teal-700">{editing?'EDIT DRUG':'NEW DRUG'}</b><h2 className="text-xl font-bold">{editing?'แก้ไขข้อมูลยา':'เพิ่มรายการยา'}</h2></div><button onClick={()=>setShowForm(false)}><X/></button></div><form onSubmit={save} className="mt-5 grid gap-4"><Field label="ชื่อยา" value={form.generic_name} onChange={v=>setForm(f=>({...f,generic_name:v}))}/><div className="grid gap-4 md:grid-cols-2"><Field label="สารละลายที่ใช้ได้ • ใช้ | ขึ้นบรรทัดใหม่" value={form.compatible_solutions} onChange={v=>setForm(f=>({...f,compatible_solutions:v}))}/><Field label="ระยะเวลาที่ฉีด • ใช้ | ขึ้นบรรทัดใหม่" value={form.injection_duration} onChange={v=>setForm(f=>({...f,injection_duration:v}))}/></div><Field label="วิธีเตรียมยา • ใช้ | ขึ้นบรรทัดใหม่" value={form.preparation_method} onChange={v=>setForm(f=>({...f,preparation_method:v}))}/><Field label="อื่นๆ / ข้อควรระวัง • ใช้ | ขึ้นบรรทัดใหม่" value={form.other_precautions} onChange={v=>setForm(f=>({...f,other_precautions:v}))}/><div className="rounded-xl bg-teal-50 p-3 text-xs text-teal-800">QR นี้จะเปิด Learning URL โดยตรงเมื่อสแกนจากกล้องมือถือหรือ LINE และสามารถใช้สแกนใน Workflow เตรียมยาได้เช่นกัน</div>{error&&<div className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</div>}<button disabled={busy} className="rounded-xl bg-teal-700 px-4 py-3 font-semibold text-white disabled:opacity-50">{busy?'กำลังบันทึก...':'บันทึกข้อมูลยา'}</button></form></div></div>}
 {card&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/70 p-4"><div className="max-h-[94vh] w-full max-w-2xl overflow-auto rounded-3xl bg-white p-5"><div className="flex items-center justify-between"><div><b className="text-xs text-teal-700">SMART ADAPTIVE CARD</b><h2 className="text-lg font-bold">{card.generic_name}</h2></div><button onClick={()=>setCard(null)}><X/></button></div><div className="mt-4 grid gap-4 md:grid-cols-[1fr_280px]"><div className="space-y-3 text-sm"><div className="rounded-xl bg-teal-50 p-3"><b>QR แบบเดียว</b><p className="mt-1 break-all text-slate-600">{learnUrl(card.id)}</p></div><div className="rounded-xl border p-3"><b>Smart Adaptive</b><p className="mt-1 text-slate-500">ระบบปรับขนาด QR และข้อความตามความยาวข้อมูล และตัดข้อความที่ยาวเกินพื้นที่ Card เพื่อไม่ให้ล้น พร้อมส่งผู้ใช้ไปยัง Learning ฉบับเต็ม</p></div></div><div className="rounded-2xl border bg-slate-50 p-3"><img src={qrUrl(card.id)} alt="QR Learning" className="mx-auto w-full max-w-[260px]"/></div></div><div className="mt-5 flex flex-wrap justify-end gap-2"><button onClick={()=>void downloadQr(card)} className="inline-flex items-center gap-2 rounded-xl bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white"><Download size={16}/>ดาวน์โหลด QR (PNG)</button><button onClick={print} className="inline-flex items-center gap-2 rounded-xl border px-4 py-2.5 text-sm font-semibold"><Printer size={16}/>พิมพ์ Card 9.5 × 20 ซม.</button></div></div></div>}
 {learn&&<div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/60 p-4"><div className="max-h-[90vh] w-full max-w-2xl overflow-auto rounded-3xl bg-white p-5"><div className="flex items-center justify-between"><div><b className="text-xs text-teal-700">LEARNING</b><h2 className="text-xl font-bold">{learn.generic_name}</h2></div><button onClick={()=>setLearn(null)}><X/></button></div><div className="mt-4 space-y-3 text-sm">{[['สารละลายที่ใช้ได้',learn.compatible_solutions],['วิธีเตรียมยา',learn.preparation_method],['ระยะเวลาที่ฉีด',learn.injection_duration],['อื่นๆ / ข้อควรระวัง',learn.other_precautions]].map(([t,v])=><div key={String(t)} className="rounded-xl bg-slate-50 p-3"><b>{String(t)}</b><div className="mt-1 whitespace-pre-wrap text-slate-600">{lines(v as string|null)}</div></div>)}</div></div></div>}
 </div>}
