import { useEffect, useMemo, useRef, useState } from 'react'
import { AlertTriangle, Camera, Check, CheckCircle2, ClipboardCheck, Pill, QrCode, RotateCcw, Search, ShieldCheck, UserRound, X } from 'lucide-react'
import { supabase } from '@/lib/supabase'

type Staff={id:string;display_code:string;full_name:string|null}
type Drug={id:string;generic_name:string;drug_group?:string|null;route?:string|null;learning_wi?:string|null;administration_guide?:string|null;patient_advice?:string|null;emergency_management?:string|null}
type Event=Record<string,any>
const statusText:Record<string,string>={pending_review:'รอตรวจสอบ',correction_required:'ต้องแก้ไข',pending_re_review:'รอตรวจซ้ำ',ready_to_administer:'พร้อมบริหารยา'}

export function KioskPage(){
 const [staff,setStaff]=useState<Staff[]>([]),[n1,setN1]=useState<Staff|null>(null),[n2,setN2]=useState<Staff|null>(null),[drug,setDrug]=useState<Drug|null>(null),[event,setEvent]=useState<Event|null>(null),[pending,setPending]=useState<Event[]>([]),[step,setStep]=useState('nurse1'),[q,setQ]=useState(''),[qr,setQr]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[answers,setAnswers]=useState<boolean[]>(Array(20).fill(false)),[camera,setCamera]=useState(false)
 const video=useRef<HTMLVideoElement>(null),stream=useRef<MediaStream|null>(null)
 const filtered=useMemo(()=>staff.filter(s=>`${s.display_code} ${s.full_name??''}`.toLowerCase().includes(q.toLowerCase())),[staff,q])
 useEffect(()=>{supabase.rpc('kiosk_list_staff').then(r=>r.error?setError(r.error.message):setStaff(r.data??[]));return()=>stopCamera()},[])
 function stopCamera(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCamera(false)}
 async function scan(value:string){setBusy(true);const r=await supabase.rpc('kiosk_get_drug',{p_qr_value:value.trim()});setBusy(false);if(r.error||!r.data)return setError(r.error?.message??'ไม่พบรายการยา');setDrug(r.data);setStep('learning')}
 async function startCamera(){if(!('BarcodeDetector'in window))return setError('เบราว์เซอร์ไม่รองรับ QR Scanner กรุณากรอกรหัส QR');try{const D=(window as any).BarcodeDetector;const detector=new D({formats:['qr_code']});stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'}},audio:false});setCamera(true);setTimeout(()=>{if(video.current){video.current.srcObject=stream.current;video.current.play().then(loop)}},50);async function loop(){if(!video.current||!stream.current)return;try{const c=await detector.detect(video.current);if(c[0]?.rawValue){stopCamera();await scan(c[0].rawValue);return}}catch{}requestAnimationFrame(loop)}}catch(e){setError(e instanceof Error?e.message:'เปิดกล้องไม่ได้')}}
 async function save(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!n1||!drug)return;setBusy(true);const f=Object.fromEntries(new FormData(e.currentTarget));const r=await supabase.rpc('kiosk_create_medication_event',{p_nurse1_id:n1.id,p_drug_id:drug.id,p_bed_code:String(f.bed_code),p_hn:String(f.hn),p_patient_name:String(f.patient_name),p_ratio_plan:String(f.ratio_plan??''),p_dose:String(f.dose),p_fluid_mixed:String(f.fluid_mixed??''),p_fluid_volume:String(f.fluid_volume??''),p_rate_ml_hr:String(f.rate_ml_hr??'')});setBusy(false);if(r.error)return setError(r.error.message);setEvent(r.data);setStep('saved')}
 async function loadPending(s:Staff){setN2(s);setBusy(true);const r=await supabase.rpc('kiosk_list_pending_events',{p_nurse_id:s.id});setBusy(false);if(r.error)return setError(r.error.message);setPending(r.data??[]);setStep('review')}
 async function review(correct:boolean){if(!event||!n2)return;setBusy(true);const note=correct?null:(prompt('ระบุรายการที่ต้องแก้ไข')||'กรุณาตรวจสอบคำสั่งแพทย์');const r=await supabase.rpc('kiosk_review_medication_event',{p_event_id:event.id,p_nurse2_id:n2.id,p_is_correct:correct,p_correction_note:note});setBusy(false);if(r.error)return setError(r.error.message);setEvent(r.data);if(correct)setStep('assessment');else{setPending(pending.filter(x=>x.id!==event.id));setStep('nurse1')}}
 async function acknowledge(){if(!event||!n1)return;setBusy(true);const r=await supabase.rpc('kiosk_acknowledge_correction',{p_event_id:event.id,p_nurse1_id:n1.id});setBusy(false);if(r.error)return setError(r.error.message);setEvent(r.data);setStep('prepare')}
 async function finish(){if(!event||!n1||!n2)return;setBusy(true);const r=await supabase.rpc('kiosk_submit_assessment',{p_event_id:event.id,p_nurse1_id:n1.id,p_nurse2_id:n2.id,p_answers:answers});setBusy(false);if(r.error)return setError(r.error.message);alert('บันทึก Medication Event และการประเมินครบถ้วนแล้ว');reset()}
 function reset(){stopCamera();setStep('nurse1');setN1(null);setN2(null);setDrug(null);setEvent(null);setPending([]);setQ('');setQr('');setAnswers(Array(20).fill(false));setError('')}
 return <div className="min-h-screen bg-slate-50 text-slate-900"><header className="sticky top-0 z-20 border-b bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between p-4"><div className="flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-teal-700 text-white"><Pill/></div><div><b>HAD Smart</b><div className="text-xs text-slate-500">ระบบนิเทศ ติดตามการบริหารยา</div></div></div><button onClick={reset} className="rounded-xl border p-2"><RotateCcw size={18}/></button></div></header><main className="mx-auto max-w-6xl p-4 md:p-8">{error&&<div className="mb-5 flex gap-3 rounded-2xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><AlertTriangle/><span>{error}</span><button className="ml-auto" onClick={()=>setError('')}><X/></button></div>}{step==='nurse1'&&<People title="เลือกพยาบาลคนที่ 1" sub="ผู้เตรียมยา / ผู้รับการนิเทศ" list={filtered} q={q} setQ={setQ} pick={s=>{setN1(s);setStep('scan')}}/>}{step==='scan'&&<Scan qr={qr} setQr={setQr} scan={()=>scan(qr)} camera={startCamera} busy={busy}/>} {step==='learning'&&drug&&<Learning drug={drug} ack={()=>setStep('prepare')}/>} {step==='prepare'&&drug&&<Prepare drug={drug} save={save} busy={busy}/>} {step==='saved'&&event&&<Saved event={event} n1={n1} acknowledge={acknowledge} goReview={()=>setStep('nurse2')} busy={busy}/>} {step==='nurse2'&&<People title="เลือกพยาบาลคนที่ 2" sub="บทบาทผู้ตรวจสอบ / ผู้นิเทศ" list={filtered.filter(x=>x.id!==n1?.id)} q={q} setQ={setQ} pick={loadPending}/>} {step==='review'&&<Review list={pending} selected={event} setSelected={setEvent} review={review} busy={busy}/>} {step==='assessment'&&<Assessment a={answers} setA={setAnswers} finish={finish} busy={busy}/>}</main>{camera&&<div className="fixed inset-0 z-50 bg-black/90 p-4"><div className="mx-auto flex h-full max-w-lg flex-col justify-center"><video ref={video} playsInline muted className="aspect-square w-full rounded-3xl object-cover"/><button onClick={stopCamera} className="mt-4 rounded-2xl bg-white p-3 font-bold">ปิดกล้อง</button></div></div>}</div>}

function People({title,sub,list,q,setQ,pick}:{title:string;sub:string;list:Staff[];q:string;setQ:(v:string)=>void;pick:(s:Staff)=>void}){return <section className="mx-auto max-w-3xl rounded-3xl border bg-white p-5 shadow-sm md:p-8"><Head icon={<UserRound/>} title={title} sub={sub}/><div className="relative mt-6"><Search size={18} className="absolute left-3 top-3.5 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ค้นหาชื่อ หรือรหัสพยาบาล..." className="w-full rounded-2xl border bg-slate-50 py-3 pl-10 pr-4"/></div><div className="mt-3 max-h-96 overflow-auto rounded-2xl border">{list.map(s=><button key={s.id} onClick={()=>pick(s)} className="flex w-full items-center gap-3 border-b p-4 text-left hover:bg-teal-50"><UserRound/><span className="flex-1"><b>{s.full_name}</b><small className="block text-slate-500">{s.display_code}</small></span><span>›</span></button>)}{!list.length&&<div className="p-8 text-center text-sm text-slate-500">ไม่พบรายชื่อ</div>}</div></section>}
function Head({icon,title,sub}:{icon:React.ReactNode;title:string;sub:string}){return <div className="flex gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-teal-50 text-teal-700">{icon}</div><div><h2 className="text-xl font-bold">{title}</h2><p className="text-sm text-slate-500">{sub}</p></div></div>}
function Scan({qr,setQr,scan,camera,busy}:{qr:string;setQr:(v:string)=>void;scan:()=>void;camera:()=>void;busy:boolean}){return <section className="mx-auto max-w-3xl rounded-3xl border bg-white p-5 shadow-sm md:p-8"><Head icon={<QrCode/>} title="สแกน QR รายการยา" sub="จาก Medication Card ที่ระบบสร้าง"/><div className="mt-7 grid gap-4 md:grid-cols-2"><button onClick={camera} className="min-h-48 rounded-3xl border-2 border-dashed border-teal-200 bg-teal-50 text-teal-800"><Camera size={40} className="mx-auto"/><b className="mt-3 block">เปิดกล้องสแกน QR</b></button><div className="rounded-3xl bg-slate-50 p-5"><b>รหัส QR สำรอง</b><div className="mt-3 flex gap-2"><input value={qr} onChange={e=>setQr(e.target.value)} className="min-w-0 flex-1 rounded-xl border p-3"/><button disabled={!qr||busy} onClick={scan} className="rounded-xl bg-teal-700 px-4 font-bold text-white">ค้นหา</button></div></div></div></section>}
function Learning({drug,ack}:{drug:Drug;ack:()=>void}){const sections=[['WI / แนวทาง',drug.learning_wi],['การบริหารยา',drug.administration_guide],['คำแนะนำผู้ป่วย',drug.patient_advice],['การจัดการภาวะฉุกเฉิน',drug.emergency_management]];return <section className="mx-auto max-w-4xl rounded-3xl border bg-white p-5 shadow-sm md:p-8"><Head icon={<ShieldCheck/>} title={`Learning: ${drug.generic_name}`} sub="ทบทวนความรู้ก่อนเตรียมและบริหารยา"/><div className="mt-6 grid gap-3 sm:grid-cols-2">{sections.map(([a,b])=><article key={a} className="rounded-2xl border p-4"><b className="text-teal-800">{a}</b><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-slate-600">{b||'ผู้ดูแลระบบยังไม่ได้กำหนดเนื้อหา'}</p></article>)}</div><button onClick={ack} className="mt-6 w-full rounded-xl bg-teal-700 p-3.5 font-bold text-white">รับทราบ และไปเตรียมยา</button></section>}
function Prepare({drug,save,busy}:{drug:Drug;save:(e:React.FormEvent<HTMLFormElement>)=>void;busy:boolean}){const fields=[['bed_code','เตียง / ห้อง'],['hn','HN'],['patient_name','ชื่อผู้ป่วย'],['ratio_plan','อัตราส่วนตามแผน'],['dose','ขนาด / ปริมาณยา'],['fluid_mixed','สารน้ำที่ผสม'],['fluid_volume','ปริมาณสารน้ำ'],['rate_ml_hr','อัตรา ml/hr']];return <section className="mx-auto max-w-4xl rounded-3xl border bg-white p-5 shadow-sm md:p-8"><Head icon={<Pill/>} title="ฟอร์มเตรียมยา" sub={`${drug.generic_name}${drug.route?` · ${drug.route}`:''}`}/><form onSubmit={save} className="mt-6 grid gap-4 md:grid-cols-2">{fields.map(([n,l])=><label key={n} className="text-sm font-semibold">{l}<input name={n} required={['bed_code','hn','patient_name','dose'].includes(n)} className="mt-1.5 w-full rounded-xl border p-3"/></label>)}<div className="md:col-span-2 rounded-2xl bg-slate-50 p-4 text-sm"><b>แนวทาง:</b> {drug.administration_guide||'ยังไม่ได้กำหนด'}</div><button disabled={busy} className="md:col-span-2 rounded-xl bg-teal-700 p-3.5 font-bold text-white">บันทึกส่งตรวจสอบ</button></form></section>}
function Saved({event,n1,acknowledge,goReview,busy}:{event:Event;n1:Staff|null;acknowledge:()=>void;goReview:()=>void;busy:boolean}){const correction=event.status==='correction_required';return <section className="mx-auto max-w-3xl rounded-3xl border bg-white p-8 text-center shadow-sm"><CheckCircle2 size={52} className="mx-auto text-emerald-600"/><h2 className="mt-3 text-xl font-bold">{correction?'รายการถูกส่งกลับเพื่อแก้ไข':'บันทึกสำเร็จ'}</h2><p className="text-sm text-slate-500">{event.drug_name} · เตียง {event.bed_code}</p>{event.correction_note&&<div className="mt-5 rounded-2xl bg-amber-50 p-4 text-left text-sm"><b>ข้อเสนอแนะ:</b> {event.correction_note}</div>}<div className="mt-5 rounded-2xl bg-slate-50 p-4 text-left text-sm">พยาบาลคนที่ 1: <b>{n1?.full_name}</b><br/>สถานะ: <b>{statusText[event.status]??event.status}</b></div>{correction?<button disabled={busy} onClick={acknowledge} className="mt-5 w-full rounded-xl bg-amber-600 p-3 font-bold text-white">รับทราบการแก้ไข</button>:<button onClick={goReview} className="mt-5 w-full rounded-xl bg-teal-700 p-3 font-bold text-white">ไปบทบาทผู้ตรวจสอบ</button>}</section>}
function Review({list,selected,setSelected,review,busy}:{list:Event[];selected:Event|null;setSelected:(e:Event)=>void;review:(ok:boolean)=>void;busy:boolean}){return <section className="mx-auto max-w-5xl"><div className="mb-4 rounded-3xl bg-violet-700 p-5 text-white"><b>บทบาทผู้ตรวจสอบ</b><div className="text-sm">ทวนกับคำสั่งแพทย์ก่อนยืนยัน</div></div><div className="grid gap-4 lg:grid-cols-[340px_1fr]"><div className="rounded-3xl border bg-white p-4"><b>รายการค้าง ({list.length})</b>{list.map(x=><button key={x.id} onClick={()=>setSelected(x)} className={`mt-2 w-full rounded-2xl border p-4 text-left ${selected?.id===x.id?'border-violet-300 bg-violet-50':''}`}><b>{x.drug_name}</b><small className="block text-slate-500">เตียง {x.bed_code} · HN {x.hn}</small><small className="font-semibold text-violet-700">{statusText[x.status]??x.status}</small></button>)}</div><div className="rounded-3xl border bg-white p-5">{selected?<><Head icon={<ClipboardCheck/>} title="ทวนกับคำสั่งแพทย์" sub="ตรวจสอบข้อมูลทุกช่อง"/><div className="mt-5 grid gap-2 sm:grid-cols-2">{Object.entries({ยา:selected.drug_name,'เตียง/ห้อง':selected.bed_code,HN:selected.hn,'ผู้ป่วย':selected.patient_name,'อัตราส่วน':selected.ratio_plan,'ขนาดยา':selected.dose,'สารน้ำ':selected.fluid_mixed,'ปริมาณสารน้ำ':selected.fluid_volume,'อัตรา':selected.rate_ml_hr}).map(([a,b])=><div key={a} className="rounded-xl bg-slate-50 p-3 text-sm"><small className="text-slate-500">{a}</small><div className="font-semibold">{String(b||'-')}</div></div>)}</div><div className="mt-5 flex gap-3"><button disabled={busy} onClick={()=>review(false)} className="flex-1 rounded-xl bg-red-50 p-3 font-bold text-red-700">ไม่ถูกต้อง — ส่งกลับแก้ไข</button><button disabled={busy} onClick={()=>review(true)} className="flex-1 rounded-xl bg-emerald-600 p-3 font-bold text-white">ถูกต้อง — ยืนยัน</button></div></>:<div className="p-10 text-center text-slate-500">เลือกรายการทางซ้าย</div>}</div></div></section>}
function Assessment({a,setA,finish,busy}:{a:boolean[];setA:(x:boolean[])=>void;finish:()=>void;busy:boolean}){const n=a.filter(Boolean).length;return <section className="mx-auto max-w-4xl rounded-3xl border bg-white p-5 shadow-sm md:p-8"><Head icon={<ClipboardCheck/>} title="ประเมินตนเอง 20 ข้อ" sub="พยาบาลคนที่ 1 = ผู้รับการนิเทศ · พยาบาลคนที่ 2 = ผู้ประเมิน/ผู้นิเทศ"/><div className="mt-5 rounded-2xl bg-teal-50 p-4"><b>ตอบแล้ว {n}/20</b></div><div className="mt-4 space-y-2">{a.map((v,i)=><button key={i} onClick={()=>{const x=[...a];x[i]=!x[i];setA(x)}} className={`flex w-full gap-3 rounded-2xl border p-4 text-left ${v?'border-emerald-200 bg-emerald-50':''}`}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-slate-100">{v?<Check size={16}/>:i+1}</span><span className="text-sm">ฉันสามารถปฏิบัติตามหลักความปลอดภัยในการบริหารยา High Alert Drug และตรวจสอบข้อมูลก่อนบริหารยาได้อย่างถูกต้อง</span></button>)}</div><button disabled={busy||n<20} onClick={finish} className="mt-6 w-full rounded-xl bg-teal-700 p-3.5 font-bold text-white disabled:opacity-40">บันทึกการประเมินและจบ Medication Event</button></section>}
