import { useEffect, useState } from 'react'
import { History, Pencil, ShieldCheck, UserPlus, X } from 'lucide-react'
import { useAuth } from '@/context/AuthContext'
import { ROLE_LABEL_TH, type NurseLevel } from '@/lib/types'
import { supabase } from '@/lib/supabase'

const NURSE_LEVEL_LABEL_TH: Record<NurseLevel, string> = { novice:'Novice', advanced_beginner:'Advanced Beginner', competent:'Competent', proficient:'Proficient', expert:'Expert' }
type AdminRow={id:string;display_code:string;full_name:string|null;is_active:boolean}
type AuditRow={id:string;actor_id:string|null;action:string;entity_type:string;entity_id:string|null;details:Record<string,unknown>|null;created_at:string}

export function ProfilePage(){
 const {profile}=useAuth();const [admins,setAdmins]=useState<AdminRow[]>([]);const [audits,setAudits]=useState<AuditRow[]>([]);const [name,setName]=useState('');const [email,setEmail]=useState('');const [code,setCode]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [editing,setEditing]=useState<AdminRow|null>(null);const [editName,setEditName]=useState('');const [editCode,setEditCode]=useState('')
 useEffect(()=>{if(profile?.role==='admin'){void loadAdmins();void loadAudits()}},[profile?.role])
 async function loadAdmins(){const r=await supabase.from('profiles').select('id,display_code,full_name,is_active').eq('role','admin').order('display_code');if(!r.error)setAdmins((r.data??[]) as AdminRow[])}
 async function loadAudits(){const r=await supabase.from('admin_audit_logs').select('id,actor_id,action,entity_type,entity_id,details,created_at').order('created_at',{ascending:false}).limit(30);if(!r.error)setAudits((r.data??[]) as AuditRow[])}
 async function addAdmin(){setError('');setMessage('');if(!name.trim()||!email.trim()){setError('กรุณาระบุชื่อและอีเมล');return}setBusy(true);const r=await supabase.functions.invoke('admin-invite-user',{body:{email:email.trim(),full_name:name.trim(),display_code:code.trim()}});setBusy(false);if(r.error){setError(r.error.message);return}setMessage('ส่งคำเชิญผู้ดูแลระบบแล้ว ผู้รับจะตั้งรหัสผ่านจากอีเมลเชิญ');setName('');setEmail('');setCode('');await loadAdmins();await loadAudits()}
 function startEdit(a:AdminRow){setEditing(a);setEditName(a.full_name??'');setEditCode(a.display_code);setError('');setMessage('')}
 async function saveEdit(){if(!editing)return;if(!editName.trim()||!editCode.trim()){setError('กรุณาระบุชื่อและ Display Code');return}setBusy(true);const r=await supabase.from('profiles').update({full_name:editName.trim(),display_code:editCode.trim()}).eq('id',editing.id);setBusy(false);if(r.error){setError(r.error.message);return}setMessage('บันทึกข้อมูลผู้ดูแลระบบแล้ว');setEditing(null);await loadAdmins();await loadAudits()}
 async function toggleAdmin(a:AdminRow){if(a.id===profile?.id){setError('ไม่สามารถปิดใช้งานบัญชีของตนเองได้');return}const next=!a.is_active;if(next===false&&admins.filter(x=>x.is_active).length<=1){setError('ต้องมีผู้ดูแลระบบที่ใช้งานได้อย่างน้อย 1 บัญชี');return}setError('');setMessage('');setBusy(true);const r=await supabase.from('profiles').update({is_active:next}).eq('id',a.id).eq('role','admin');setBusy(false);if(r.error){setError(r.error.message);return}setMessage(next?'เปิดใช้งานผู้ดูแลระบบแล้ว':'ปิดใช้งานผู้ดูแลระบบแล้ว');await loadAdmins();await loadAudits()}
 if(!profile)return null
 const rows:Array<[string,string]>=[['รหัสผู้ใช้',profile.display_code],['บทบาท',ROLE_LABEL_TH[profile.role]]];if(profile.nurse_level)rows.push(['ระดับความสามารถ',NURSE_LEVEL_LABEL_TH[profile.nurse_level]])
 const auditText=(a:AuditRow)=>{const d=a.details??{};const name=typeof d.full_name==='string'?d.full_name:typeof d.generic_name==='string'?d.generic_name:'รายการ';const code=typeof d.display_code==='string'?d.display_code:'';return `${name}${code?` (${code})`:''}`}
 const actionLabel=(a:string)=>({create:'เพิ่ม',update:'แก้ไข',delete:'ลบ'}[a]??a)
 return <div className="max-w-5xl space-y-6"><h1 className="text-xl font-semibold text-ink">โปรไฟล์</h1><div className="divide-y divide-border overflow-hidden rounded-lg border border-border bg-surface">{rows.map(([label,value])=><div key={label} className="flex items-center justify-between px-4 py-3"><span className="text-sm text-ink-muted">{label}</span><span className="text-sm font-medium text-ink">{value}</span></div>)}</div><p className="text-xs leading-relaxed text-ink-muted">การแก้ไขบทบาทหรือหอผู้ป่วยของบัญชีนี้ต้องดำเนินการโดยผู้ดูแลระบบเท่านั้น</p>
 {profile.role==='admin'&&<section className="space-y-5 rounded-2xl border border-border bg-surface p-5"><div className="flex items-center gap-2"><ShieldCheck size={19}/><div><h2 className="font-semibold text-ink">จัดการผู้ดูแลระบบ</h2><p className="text-xs text-ink-muted">เพิ่ม แก้ไข และเปิด/ปิดใช้งานบัญชีผู้ดูแลระบบ</p></div></div>
 <div className="grid gap-3 md:grid-cols-3"><input value={name} onChange={e=>setName(e.target.value)} placeholder="ชื่อ-นามสกุล" className="rounded-xl border border-border bg-white px-3 py-2.5"/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="Email สำหรับเชิญ" className="rounded-xl border border-border bg-white px-3 py-2.5"/><input value={code} onChange={e=>setCode(e.target.value)} placeholder="รหัสผู้ดูแล (ถ้ามี)" className="rounded-xl border border-border bg-white px-3 py-2.5"/></div><button disabled={busy} onClick={()=>void addAdmin()} className="inline-flex items-center gap-2 rounded-xl bg-accent px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50"><UserPlus size={17}/>{busy?'กำลังดำเนินการ…':'เพิ่มผู้ดูแลระบบ'}</button>
 {message&&<p className="text-sm text-emerald-700">{message}</p>}{error&&<p className="text-sm text-red-600">{error}</p>}
 <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-sm"><thead><tr className="border-b border-border text-left text-xs text-ink-muted"><th className="py-2">ผู้ดูแล</th><th>รหัส</th><th>สถานะ</th><th className="text-right">จัดการ</th></tr></thead><tbody>{admins.map(a=><tr key={a.id} className="border-b border-border/70"><td className="py-3">{a.full_name||'ไม่ระบุชื่อ'}</td><td>{a.display_code}</td><td><span className={a.is_active?'text-emerald-700':'text-red-600'}>{a.is_active?'ใช้งาน':'ปิดใช้งาน'}</span></td><td><div className="flex justify-end gap-2"><button onClick={()=>startEdit(a)} className="inline-flex items-center gap-1 rounded-lg border border-border px-2.5 py-1.5 text-xs"><Pencil size={14}/>แก้ไข</button><button disabled={busy||a.id===profile.id} onClick={()=>void toggleAdmin(a)} className="rounded-lg border border-border px-2.5 py-1.5 text-xs disabled:opacity-40">{a.is_active?'ปิดใช้งาน':'เปิดใช้งาน'}</button></div></td></tr>)}</tbody></table></div>
 {editing&&<div className="rounded-xl border border-accent/30 bg-accent-soft/40 p-4"><div className="mb-3 flex items-center justify-between"><p className="text-sm font-semibold">แก้ไขผู้ดูแลระบบ: {editing.display_code}</p><button onClick={()=>setEditing(null)}><X size={17}/></button></div><div className="grid gap-3 md:grid-cols-2"><input value={editName} onChange={e=>setEditName(e.target.value)} placeholder="ชื่อ-นามสกุล" className="rounded-xl border border-border bg-white px-3 py-2.5 text-sm"/><input value={editCode} onChange={e=>setEditCode(e.target.value)} placeholder="Display Code" className="rounded-xl border border-border bg-white px-3 py-2.5 text-sm"/></div><button disabled={busy} onClick={()=>void saveEdit()} className="mt-3 rounded-xl bg-accent px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">บันทึก</button></div>}
 </section>}
 {profile.role==='admin'&&<section className="rounded-2xl border border-border bg-surface p-5"><div className="mb-4 flex items-center gap-2"><History size={19}/><div><h2 className="font-semibold text-ink">Audit Log</h2><p className="text-xs text-ink-muted">ประวัติการจัดการผู้ดูแลระบบและรายการยา 30 รายการล่าสุด</p></div></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-xs"><thead><tr className="border-b border-border text-left text-ink-muted"><th className="py-2">วันเวลา</th><th>ผู้ดำเนินการ</th><th>กิจกรรม</th><th>รายการ</th></tr></thead><tbody>{audits.map(a=><tr key={a.id} className="border-b border-border/70"><td className="py-2.5">{new Date(a.created_at).toLocaleString('th-TH')}</td><td>{a.actor_id===profile.id?'ฉัน':a.actor_id?.slice(0,8)??'-'}</td><td>{actionLabel(a.action)}</td><td>{a.entity_type==='had_drugs'?'รายการยา':'ผู้ดูแลระบบ'} • {auditText(a)}</td></tr>)}</tbody></table>{audits.length===0&&<p className="py-6 text-center text-sm text-ink-muted">ยังไม่มีประวัติ</p>}</div></section>}
 </div>
}
